///<reference path='all.d.ts' />

var ASSERT_ACTIVE: number;
var ASSERT_WARNING: number;
var ASSERT_BAIL: number;
var ASSERT_QUIET_EVAL: number;
var ASSERT_CALLBACK: number;

var CREDITS_ALL: number;
var CREDITS_DOC: number;
var CREDITS_FULLPAGE: number;
var CREDITS_GENERAL: number;
var CREDITS_GROUP: number;
var CREDITS_MODULES: number;
var CREDITS_SAPI: number;

var INFO_GENERAL: number;
var INFO_CREDITS: number;
var INFO_CONFIGURATION: number;
var INFO_MODULES: number;
var INFO_ENVIRONMENT: number;
var INFO_VARIABLES: number;
var INFO_LICENSE: number;
var INFO_ALL: number;

function assert_options(what: number, value?: any): any;
function assert(assertion: bool, description?: string): bool;
function assert(assertion: string, description?: string): bool;
function dl(library: string): bool;
function extension_loaded(name: string): bool;
function gc_collect_cycles(): number;
function gc_disable();
function gc_enable();
function gc_enabled(): bool;
function get_cfg_var(option: string): string;
function get_current_user(): string;
function get_defined_constants(categorize?: bool): Pct.PhpAssocArray;
function get_extension_funcs(module_name: string): string[];
function get_include_path(): string;
function get_included_files(): string[];
function get_loaded_extensions(zend_extensions?: bool): string[];
function getenv(varname: string): string;
function getlastmod(): number;
function getmygid(): number;
function getmyinode(): number;
function getmypid(): number;
function getmyuid(): number;
function getopt(options: string, longopts?: Array): Pct.PhpAssocArray;
function getrusage(who?: number): Pct.PhpAssocArray;
function ini_get(varname: string): string;
function ini_get_all(extension?: string, details?: bool): Pct.PhpAssocArray;
function ini_restore(varname: string);
function ini_set(varname: string, newvalue: string): string;
function memory_get_peak_usage(real_usage?: bool): number;
function memory_get_usage(real_usage?: bool): number;
function php_ini_loaded_file(): string;
function php_ini_scanned_files(): string;
function php_logo_guid(): string;
function php_sapi_name(): string;
function php_uname(mode?: string): string;
function phpcredits(flag?: number): bool;
function phpinfo(what?: number): bool;
function phpversion(extension?: string): string;
function putenv(setting: string): bool;
function restore_include_path();
function set_include_path(new_include_path: string): string;
function set_time_limit(seconds: number);
function sys_get_temp_dir(): string;
function version_compare(version1: string, version2: string): number;
function version_compare(version1: string, version2: string, operator: string): bool;
function zend_logo_guid(): string;
function zend_thread_id(): number;
function zend_version(): string;