///<reference path='all.d.ts' />

var INF: number;
var NAN: number;

var M_1_PI: number;
var M_2_PI: number;
var M_2_SQRTPI: number;
var M_E: number;
var M_EULER: number;
var M_LN10: number;
var M_LN2: number;
var M_LNPI: number;
var M_LOG10E: number;
var M_LOG2E: number;
var M_PI: number;
var M_PI_2: number;
var M_PI_4: number;
var M_SQRT1_2: number;
var M_SQRT2: number;
var M_SQRT3: number;
var M_SQRTPI: number;

var PHP_ROUND_HALF_DOWN: number;
var PHP_ROUND_HALF_EVEN: number;
var PHP_ROUND_HALF_ODD: number;
var PHP_ROUND_HALF_UP: number;

function abs(number_: number): number;
function acos(arg: number): number;
function acosh(arg: number): number;
function asin(arg: number): number;
function asinh(arg: number): number;
function atan(arg: number): number;
function atan2(y: number, x: number): number;
function atanh(arg: number): number;
function base_convert(number: string, frombase: number, tobase: number): string;
function bindec(binary_string: string): number;
function ceil(value: number): number;
function cos(arg: number): number;
function cosh(arg: number): number;
function decbin(number_: number): string;
function dechex(number_: number): string;
function decoct(number_: number): string;
function deg2rad(number_: number): number;
function exp(arg: number): number;
function expm1(arg: number): number;
function floor(value: number): number;
function fmod(x: number, y: number): number;
function getrandmax(): number;
function hexdec(hex_string: string): number;
function hypot(x: number, y: number): number;
function is_finite(val: number): bool;
function is_infinite(val: number): bool;
function is_nan(val: number): bool;
function lcg_value(): number;
function log(arg: number, base?: number): number;
function log10(arg: number): number;
function log1p(arg: number): number;
function max(values: any[]): any;
function max(value1: any, value2: any, ...values: any[]): any;
function min(values: any[]): any;
function min(value1: any, value2: any, ...values: any[]): any;
function mt_getrandmax(): number;
function mt_rand(): number;
function mt_rand(min: number, max: number): number;
function mt_srand(seed?: number);
function octdec(octal_string: string): number;
function pi(): number;
function pow(base: number, exp: number): number;
function rad2deg(number_: number): number;
function rand(): number;
function rand(min: number, max: number): number;
function round(val: number, precision?: number, mode?: number): number;
function sin(arg: number): number;
function sinh(arg: number): number;
function sqrt(arg: number): number;
function srand(seed?: number);
function tan(arg: number): number;
function tanh(arg: number): number;