///<reference path='all.d.ts' />

var PCRE_VERSION: number;
var PREG_BACKTRACK_LIMIT_ERROR: number;
var PREG_BAD_UTF8_ERROR: number;
var PREG_BAD_UTF8_OFFSET_ERROR: number;
var PREG_INTERNAL_ERROR: number;
var PREG_NO_ERROR: number;
var PREG_OFFSET_CAPTURE: number;
var PREG_PATTERN_ORDER: number;
var PREG_RECURSION_LIMIT_ERROR: number;
var PREG_SET_ORDER: number;
var PREG_SPLIT_DELIM_CAPTURE: number;
var PREG_SPLIT_NO_EMPTY: number;
var PREG_SPLIT_OFFSET_CAPTURE: number;

function preg_filter(pattern: string, replacement: string, subject: string, limit?: number, $count?: number): string;
function preg_filter(pattern: string[], replacement: string, subject: string, limit?: number, $count?: number): string;
function preg_filter(pattern: string, replacement: string[], subject: string, limit?: number, $count?: number): string;
function preg_filter(pattern: string[], replacement: string[], subject: string, limit?: number, $count?: number): string;
function preg_filter(pattern: string, replacement: string, subject: string[], limit?: number, $count?: number): string[];
function preg_filter(pattern: string, replacement: string[], subject: string[], limit?: number, $count?: number): string[];
function preg_filter(pattern: string[], replacement: string, subject: string[], limit?: number, $count?: number): string[];
function preg_filter(pattern: string[], replacement: string[], subject: string[], limit?: number, $count?: number): string[];
function preg_grep(pattern: string, input: Array, flags?: number): Array;
function preg_last_error(): number;
function preg_match(pattern: string, subject: string, $matches?: Array, flags?: number, offset?: number): number;
function preg_match_all(pattern: string, subject: string, $matches?: Array, flags?: number, offset?: number): number;
function preg_quote(str: string, delimiter?: string): string;
function preg_replace(pattern: string, replacement: string, subject: string, limit?: number, $count?: number): string;
function preg_replace(pattern: string[], replacement: string, subject: string, limit?: number, $count?: number): string;
function preg_replace(pattern: string, replacement: string[], subject: string, limit?: number, $count?: number): string;
function preg_replace(pattern: string[], replacement: string[], subject: string, limit?: number, $count?: number): string;
function preg_replace(pattern: string, replacement: string, subject: string[], limit?: number, $count?: number): string[];
function preg_replace(pattern: string, replacement: string[], subject: string[], limit?: number, $count?: number): string[];
function preg_replace(pattern: string[], replacement: string, subject: string[], limit?: number, $count?: number): string[];
function preg_replace(pattern: string[], replacement: string[], subject: string[], limit?: number, $count?: number): string[];
function preg_replace_callback(pattern: string, replacement: (matches: string[]) => string, subject: string, limit?: number, $count?: number): string;
function preg_replace_callback(pattern: string[], replacement: (matches: string[]) => string, subject: string, limit?: number, $count?: number): string;
function preg_replace_callback(pattern: string, replacement: (matches: string[]) => string, subject: string[], limit?: number, $count?: number): string[];
function preg_replace_callback(pattern: string[], replacement: (matches: string[]) => string, subject: string[], limit?: number, $count?: number): string[];
function preg_split(pattern: string, subject: string, limit?: number, flags?: number): any[];