///<reference path='all.d.ts' />

var HTML_ENTITIES: number;
var HTML_SPECIALCHARS: number;

var ENT_COMPAT: number;
var ENT_QUOTES: number;
var ENT_NOQUOTES: number;
var ENT_IGNORE: number;
var ENT_SUBSTITUTE: number;
var ENT_DISALLOWED: number;
var ENT_HTML401: number;
var ENT_XML1: number;
var ENT_XHTML: number;
var ENT_HTML5: number;

var LC_ALL: number;
var LC_COLLATE: number;
var LC_CTYPE: number;
var LC_MONETARY: number;
var LC_NUMERIC: number;
var LC_TIME: number;
var LC_MESSAGES: number;

var STR_PAD_RIGHT: number;
var STR_PAD_LEFT: number;
var STR_PAD_BOTH: number;

function addcslashes(str: string, charlist: string): string;
function addslashes(str: string): string;
function bin2hex(str: string): string;
function chr(ascii: number): string;
function chunk_split(body: string, chunklen?: number, end?: string): string;
function convert_cyr_string(str: string, from: string, to: string): string;
function convert_uudecode(data: string): string;
function convert_uuencode(data: string): string;
function count_chars(string: string, mode?: number): any;
function crc32(str: string): number;
function crypt(str: string, salt: string): string;
function echo(...str: any[]): string;
function explode(delimiter: string, string: string, limit?: number): string[];
function fprintf(handle: Pct.PhpResource, format: string, ...args: any[]): number;
function get_html_translation_table(table?: number, flags?: number, encoding?: string): Pct.PhpAssocArray;
function hebrev(hebrew_text: string, max_chars_per_line?: number): string;
function hebrevc(hebrew_text: string, max_chars_per_line?: number): string;
function hex2bin(data: string): string;
function html_entity_decode(string: string, flags?: number, encoding?: string): string;
function htmlentities(string: string, flags?: number, encoding?: string, double_encode?: bool): string;
function htmlspecialchars(string: string, flags?: number, encoding?: string, double_encode?: bool): string;
function htmlspecialchars_decode(string: string, flags?: number): string;
function implode(glue: string, pieces: Array): string;
function implode(pieces: Array): string;
function lcfirst(str: string): string;
function levenshtein(str1: string, str2: string): number;
function levenshtein(str1: string, str2: string, const_ins: number, cost_rep: number, cost_del: number);
function localconv(): Pct.PhpAssocArray;
function ltrim(str: string, charlist?: string): string;
function md5(str: string, raw_output?: bool): string;
function md5_file(filename: string, raw_output?: bool): string;
function metaphone(str: string, phonemes?: number): string;
function money_format(format: string, number: number): string;
function nl_langinfo(item: number): string; //TODO enum for last param
function nl2br(string: string, is_xhtml?: bool): string;
function number_format(number: number, decimals?: number, dec_point?: string, thousands_sep?: string): string;
function ord(string: string): number;
function parse_str(str: string, $arr: Pct.PhpAssocArray); //we require an array because we don't have ability to set var in current scope and don't want it
function print(arg: any): number;
function printf(format: string, ...args: any[]): number;
function quoted_printable_decode(str: string): string;
function quoted_printable_encode(str: string): string;
function quotemeta(str: string): string;
function rtrim(str: string, charlist?: string): string;
function setlocale(category: number, locale: string, ...settings: string[]): string;
function setlocale(category: number, locale: Array): string;
function sha1(str: string, raw_output?: bool): string;
function sha1_file(filename: string, raw_output?: bool): string;
function similar_text(first: string, second: string, $percent?: number): number;
function soundex(str: string): string;
function sprintf(format: string, ...args: any[]): string;
function sscanf(str: string, format: string, ...$vars: any[]): any;
function str_getcsv(input: string, delimiter?: string, enclosure?: string, escape?: string): string[];
function str_ireplace(search: string, replace: string, subject: string, $count?: number): string;
function str_ireplace(search: any[], replace: string, subject: string, $count?: number): string;
function str_ireplace(search: any[], replace: any[], subject: string, $count?: number): string;
function str_ireplace(search: any[], replace: any[], subject: any[], $count?: number): string[];
function str_ireplace(search: string, replace: any[], subject: string, $count?: number): string;
function str_ireplace(search: string, replace: any[], subject: any[], $count?: number): string;
function str_ireplace(search: string, replace: string, subject: any[], $count?: number): string;
function str_pad(input: string, pad_length: number, pad_string?: string, pad_type?: number): string;
function str_repeat(input: string, multiplier: number): string;
function str_replace(search: string, replace: string, subject: string, $count?: number): string;
function str_replace(search: any[], replace: string, subject: string, $count?: number): string;
function str_replace(search: any[], replace: any[], subject: string, $count?: number): string;
function str_replace(search: any[], replace: any[], subject: any[], $count?: number): string[];
function str_replace(search: string, replace: any[], subject: string, $count?: number): string;
function str_replace(search: string, replace: any[], subject: any[], $count?: number): string;
function str_replace(search: string, replace: string, subject: any[], $count?: number): string;
function str_rot13(str: string): string;
function str_shuffle(str: string): string;
function str_split(str: string, split_length?: number): string[];
function str_word_count(string: string, format?: number, charlist?: string): any; //number or array
function strcasecmp(str1: string, str2: string): number;
function strcmp(str1: string, str2: string): number;
function strcoll(str1: string, str2: string): number;
function strcspn(str1: string, str2: string, start?: number, length?: number): number;
function strip_tags(str: string, allowable_tags?: string): string;
function stripcslashes(str: string): string;
function stripos(haystack: string, needle: string, offset?: number): number;
function stripos(haystack: string, needle: number, offset?: number): number;
function stripslashes(str: string): string;
function stristr(haystack: string, needle: string, before_needle?: bool): string;
function stristr(haystack: string, needle: number, before_needle?: bool): string;
function strlen(string: string): number;
function strnatcasecmp(str1: string, str2: string): number;
function strnatcmp(str1: string, str2: string): number;
function strncasecmp(str1: string, str2: string, len: number): number;
function strncmp(str1: string, str2: string, len: number): number;
function strpbrk(haystack: string, char_list: string): string;
function strpos(haystack: string, needle: string, offset?: number): number;
function strpos(haystack: string, needle: number, offset?: number): number;
function strrchr(haystack: string, needle: string): string;
function strrchr(haystack: string, needle: number): string;
function strrev(string: string): string;
function strripos(haystack: string, needle: string, offset?: number): number;
function strripos(haystack: string, needle: number, offset?: number): number;
function strrpos(haystack: string, needle: string, offset?: number): number;
function strrpos(haystack: string, needle: number, offset?: number): number;
function strspn(subject: string, mask: string, start?: number, length?: number): number;
function strstr(haystack: string, needle: string, before_needle?: bool): string;
function strstr(haystack: string, needle: number, before_needle?: bool): string;
function strtok(str: string, token: string): string;
function strtok(token: string): string;
function strtolower(str: string): string;
function strtoupper(string: string): string;
function strtr(str: string, from: string, to: string): string;
function strtr(str: string, replace_pairs: Pct.PhpAssocArray): string;
function substr(string: string, start: number, length?: number): string;
function substr_compare(main_str: string, str: string, offset: number, length?: number, case_sensitivity?: bool): number;
function substr_count(haystack: string, needle: string, offset?: number, length?: number): number;
function substr_replace(string: string, replacement: string, start: number, length?: number): string;
function substr_replace(string: string[], replacement: string, start: number, length?: number): string[];
function substr_replace(string: string[], replacement: string[], start: number, length?: number): string[];
function substr_replace(string: string[], replacement: string, start: number[], length?: number): string[];
function substr_replace(string: string[], replacement: string[], start: number[], length?: number): string[];
function substr_replace(string: string[], replacement: string, start: number, length?: number[]): string[];
function substr_replace(string: string[], replacement: string[], start: number, length?: number[]): string[];
function substr_replace(string: string[], replacement: string, start: number[], length?: number[]): string[];
function substr_replace(string: string[], replacement: string[], start: number[], length?: number[]): string[];
function trim(str: string, charlist?: string): string;
function ucfirst(str: string): string;
function ucwords(str: string): string;
function vfprintf(handle: Pct.PhpResource, format: string, args: Array): number;
function vprintf(format: string, args: Array): number;
function vsprintf(format: string, args: Array): string;
function wordwrap(str: string, width?: number, break_?: string, cut?: bool): string;